### PR TITLE
Fixed the need for cmp function for both python3 and python2

### PR DESCRIPTION
**Pull request by PandaWhoCodes**
Travis CI Build Successfull.

### CODE REVIEW

**Comment by AGausmann** [comment]
Thanks Panda, I am in need of this fix as well.

**Comment by joshvillbrandt** [comment]
I’ll get this merged on Monday. Thanks, guys!!

Josh

**Comment by PandaWhoCodes** [comment]
for some reason my commit on 
https://github.com/PandaWhoCodes/wireless/blob/master/wireless/Wireless.py
is not being displayed.

**Comment by joshvillbrandt** [comment]
Hey @PandaWhoCodes, maybe your having some trouble with git? Maybe reset to the HEAD of #develop and force push to your branch? Ideally you'd be submitted just one commit for merge, not three.

Also, I just merged #15 which might alleviate your issue in the first place.

**Pull request closed without merging**
