### PR TITLE
Add version check for nmcli, bump version

### PR DESCRIPTION
**Pull request by Silarn**
As of NetworkManager 0.9.9.0, many of the old nmcli commands have changed. This was breaking the script for me. I'm not an experienced python coder, so this might be a bit dirty and hacky, but it works for me.

That said, it might be better to simply run the version check when the commands are run rather than creating a new driver with a lot of duplicate code.

### CODE REVIEW

**Comment by Silarn** [comment]
Is there any change I could make to get this pulled in? I can revert the version bump, which was probably unnecessary for now. Without this addition, the script does not work with newer NetworkManager versions.

**Comment by joshvillbrandt** [comment]
Hey @Silarn, thanks for using `wireless` and submitting this pull request! This must have slipped through my email - just looking through this for the first time now.

I think this all seems fine. I wish I had tests for all of this with mocks for each driver type, but alas, that sounds like a lot of work.

Out of curiosity, which operating systems come with NetworkManager >= 0.9.9.0?

**Comment by Silarn** [comment]
I know that Ubuntu 15.04 and Fedora at least back to 21 are on it. 





On Mon, Jun 1, 2015 at 2:13 PM -0700, "Josh Villbrandt" <notifications@github.com> wrote:












Hey @Silarn, thanks for using wireless and submitting this pull request! This must have slipped through my email - just looking through this for the first time now.



I think this all seems fine. I wish I had tests for all of this with mocks for each driver type, but alas, that sounds like a lot of work.



Out of curiosity, which operating systems come with NetworkManager >= 0.9.9.0?

**Comment by joshvillbrandt** [comment]
Checking my understanding here - with your changes, the wireless library now functions as expected for both old and new NetworkManager versions, correct?

**Comment by Silarn** [comment]
It should. The code for earlier versions is identical, and I have a working gopro setup working on my modified version of the library. I tested each command in the driver and replaced with a working alternate when it failed. Fortunately, the command output is still very similar still.



On Mon, Jun 1, 2015 at 5:52 PM -0700, "Josh Villbrandt" <notifications@github.com> wrote:












Checking my understanding here - with your changes, the wireless library now functions as expected for both old and new NetworkManager versions, correct?

**Comment by joshvillbrandt** [comment]
@Silarn, please do the PR to the develop branch next time. Thanks!

**Pull request merged**
